import type { CampusLocation, DemoState, ItemReport, Profile } from './types';
export const LOCATIONS: CampusLocation[] = [
  { id: 'library', name: 'University Library', zone: 'central' },
  { id: 'cafeteria', name: 'Campus Cafeteria', zone: 'central' },
  { id: 'main-gate', name: 'Main Entrance', zone: 'south' },
  { id: 'science', name: 'Science Building', zone: 'academic' },
  { id: 'classroom', name: 'Academic Building', zone: 'academic' },
  { id: 'gym', name: 'Sports Center', zone: 'north' },
  { id: 'garden', name: 'Central Courtyard', zone: 'central' },
  { id: 'parking', name: 'Student Parking', zone: 'south' },
];
export const PROFILES: Profile[] = [
  {
    id: 'jamie',
    name: 'Jamie Santos',
    email: 'jamie@westbridge.edu.ph',
    schoolId: '2024-01482',
    role: 'student',
  },
  {
    id: 'mika',
    name: 'Mika Reyes',
    email: 'mika@westbridge.edu.ph',
    schoolId: '2023-00836',
    role: 'student',
  },
  {
    id: 'staff',
    name: 'Alex Rivera',
    email: 'alex@westbridge.edu.ph',
    schoolId: 'ST-00124',
    role: 'staff',
  },
  {
    id: 'security',
    name: 'Officer Cruz',
    email: 'security@westbridge.edu.ph',
    schoolId: 'SEC-0018',
    role: 'security',
  },
];
const base = (id: string, values: Partial<ItemReport>): ItemReport => ({
  id,
  reference: `FC-2026-${id.padStart(4, '0')}`,
  reporterId: 'mika',
  type: 'found',
  title: '',
  description: '',
  category: 'Other',
  color: 'Black',
  brand: '',
  identifyingFeatures: '',
  date: '2026-08-28',
  time: '09:30',
  locationId: 'library',
  imageUrl: '',
  status: 'Reported',
  storageLocation: 'Security Office · Cabinet A',
  contactPreference: 'In-app notifications',
  createdAt: '2026-08-28T01:30:00.000Z',
  updatedAt: '2026-08-28T01:30:00.000Z',
  ...values,
});
export function createSeed(): DemoState {
  return {
    version: 1,
    profiles: PROFILES,
    currentUserId: 'jamie',
    saved: { jamie: ['102'] },
    reports: [
      base('101', {
        title: 'Blue umbrella',
        category: 'Umbrellas',
        color: 'Blue',
        locationId: 'main-gate',
        imageUrl: '/images/umbrella.webp',
        description:
          'A folded navy blue umbrella with a curved wooden handle. Found near the covered walkway by the main entrance.',
        identifyingFeatures: 'Small silver star sticker inside the handle.',
      }),
      base('102', {
        title: 'Wireless earbuds',
        category: 'Electronics',
        color: 'White',
        brand: 'Apple',
        locationId: 'classroom',
        imageUrl: '/images/earbuds.webp',
        description:
          'A pair of white wireless earbuds in their charging case. Found on a desk in the Academic Building.',
        identifyingFeatures: 'The initials MR are engraved under the case.',
        time: '08:45',
      }),
      base('103', {
        title: 'Student ID card',
        category: 'ID & cards',
        color: 'Green',
        locationId: 'library',
        imageUrl: '/images/id-card.webp',
        description:
          'A student ID in a clear holder with a green lanyard. Found near the library entrance. Personal details are kept private.',
        identifyingFeatures: 'Card name: Jamie Santos. ID ends in 1482.',
        status: 'Under Review',
        time: '08:10',
      }),
      base('104', {
        title: 'Scientific calculator',
        category: 'Electronics',
        color: 'Black',
        brand: 'Casio',
        locationId: 'science',
        imageUrl: '/images/calculator.webp',
        description:
          'A black scientific calculator with a slide-on cover. Found after a laboratory class in the Science Building.',
        identifyingFeatures:
          'Small scratch near the solar panel; JS written inside the cover.',
        status: 'Possible Match',
        date: '2026-08-27',
        time: '16:20',
        createdAt: '2026-08-27T08:20:00.000Z',
      }),
      base('105', {
        title: 'Motorcycle keys',
        category: 'Keys',
        color: 'Black',
        locationId: 'cafeteria',
        description:
          'Two keys with a black motorcycle key fob, found near the cafeteria counter.',
        identifyingFeatures: 'A small red woven keychain.',
        date: '2026-08-27',
        createdAt: '2026-08-27T06:00:00.000Z',
      }),
      base('106', {
        title: 'Canvas tote bag',
        category: 'Bags',
        color: 'Cream',
        locationId: 'garden',
        description: 'Plain cream canvas tote left on a courtyard bench.',
        date: '2026-08-25',
        status: 'Unclaimed',
        createdAt: '2026-08-25T06:00:00.000Z',
      }),
      base('107', {
        title: 'Blue water bottle',
        category: 'Other',
        color: 'Blue',
        locationId: 'gym',
        description: 'A reusable blue water bottle found at the Sports Center.',
        date: '2026-08-24',
        status: 'Returned',
        createdAt: '2026-08-24T06:00:00.000Z',
      }),
      base('108', {
        title: 'Reading glasses',
        category: 'Other',
        color: 'Black',
        locationId: 'library',
        description: 'Black reading glasses in a brown hard case.',
        date: '2026-08-23',
        status: 'Returned',
        createdAt: '2026-08-23T06:00:00.000Z',
      }),
      base('201', {
        reporterId: 'jamie',
        type: 'lost',
        title: 'Casio scientific calculator',
        category: 'Electronics',
        color: 'Black',
        brand: 'Casio',
        locationId: 'science',
        imageUrl: '/images/calculator.webp',
        description:
          'My black scientific calculator with a slide-on cover, last used during our laboratory class.',
        identifyingFeatures:
          'JS written inside the cover; scratch near solar panel.',
        date: '2026-08-26',
        time: '14:00',
        status: 'Possible Match',
        storageLocation: '',
        createdAt: '2026-08-26T07:00:00.000Z',
      }),
      base('202', {
        reporterId: 'jamie',
        type: 'lost',
        title: 'Motorcycle keys',
        category: 'Keys',
        color: 'Black',
        locationId: 'cafeteria',
        description:
          'Two keys with a black motorcycle key fob. Last seen during lunch at the cafeteria.',
        identifyingFeatures: 'A red woven keychain.',
        date: '2026-08-27',
        time: '12:00',
        status: 'Possible Match',
        storageLocation: '',
        createdAt: '2026-08-27T05:00:00.000Z',
      }),
      base('203', {
        reporterId: 'jamie',
        type: 'found',
        title: 'Black notebook',
        category: 'Books & stationery',
        color: 'Black',
        locationId: 'library',
        description:
          'A lined black notebook found on the second floor reading table.',
        date: '2026-08-25',
        status: 'Returned',
        createdAt: '2026-08-25T05:00:00.000Z',
      }),
      base('204', {
        reporterId: 'mika',
        type: 'lost',
        title: 'White wireless earbuds',
        category: 'Electronics',
        color: 'White',
        brand: 'Apple',
        locationId: 'classroom',
        imageUrl: '/images/earbuds.webp',
        description:
          'White wireless earbuds with charging case, left in class.',
        date: '2026-08-27',
        status: 'Possible Match',
        storageLocation: '',
      }),
    ],
    claims: [
      {
        id: 'claim-1',
        reportId: '103',
        claimantId: 'jamie',
        details: 'My name is Jamie Santos. My student number ends in 1482.',
        contents: 'The green lanyard has a small safety pin on the back.',
        proof: 'I can show my school portal and another photo ID at pickup.',
        imageUrl: '',
        status: 'Under Review',
        createdAt: '2026-08-28T02:00:00.000Z',
        reviewNote: '',
      },
      {
        id: 'claim-2',
        reportId: '102',
        claimantId: 'mika',
        details: 'The initials MR are engraved underneath the charging case.',
        contents: 'Both earbuds are inside.',
        proof: 'I can show the Bluetooth pairing and purchase receipt.',
        imageUrl: '',
        status: 'Under Review',
        createdAt: '2026-08-28T01:50:00.000Z',
        reviewNote: '',
      },
    ],
    notifications: [
      {
        id: 'notice-1',
        userId: 'jamie',
        title: 'Your calculator might be here',
        message:
          'A calculator found in the Science Building matches your lost report. Take a closer look.',
        type: 'match',
        reportId: '104',
        read: false,
        createdAt: '2026-08-28T01:30:00.000Z',
      },
      {
        id: 'notice-2',
        userId: 'jamie',
        title: 'A possible match for your keys',
        message: 'Motorcycle keys were found near the Campus Cafeteria.',
        type: 'match',
        reportId: '105',
        read: false,
        createdAt: '2026-08-27T07:00:00.000Z',
      },
      {
        id: 'notice-3',
        userId: 'jamie',
        title: 'Your claim is with campus security',
        message:
          'We received your claim for the student ID card. You will be notified after review.',
        type: 'claim',
        reportId: '103',
        read: false,
        createdAt: '2026-08-28T02:00:00.000Z',
      },
      {
        id: 'notice-4',
        userId: 'jamie',
        title: 'One less thing lost',
        message:
          'The black notebook you found has been reunited with its owner. Thank you!',
        type: 'returned',
        reportId: '203',
        read: true,
        createdAt: '2026-08-26T02:00:00.000Z',
      },
    ],
    logs: [
      {
        id: 'log-1',
        actorId: 'security',
        message: 'Black notebook returned to its verified owner.',
        createdAt: '2026-08-26T02:00:00.000Z',
      },
      {
        id: 'log-2',
        actorId: 'jamie',
        message: 'Ownership claim submitted for Student ID card.',
        createdAt: '2026-08-28T02:00:00.000Z',
      },
    ],
  };
}
export const locationName = (id: string) =>
  LOCATIONS.find((l) => l.id === id)?.name || 'Campus';
export function formatDate(date: string) {
  return new Date(date.slice(0, 10) + 'T12:00:00').toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
  });
}
